.TH XTRACER 1 "December 2010" UNIX "User Manuals"
.SH NAME 
xtracer
.SH SYNOPSIS
.B xtracer [
.I option
]... 
.B file
.SH DESCRIPTION
A basic raytracing.
.SH OPTIONS
.IP "-res %ix%i"
Sets the output buffer resolution.
.IP "-depth %i"
Sets the maximum recursion depth.
.IP "-drv %s"
Sets the output driver to use. Available drivers are: ppm, sdl, dum.
.IP	"-gamma %f"
Sets the gamma correction.
.IP "-cam %s"
Sets the active camera.
.IP "-lightpos"
Renders the point lights as spheres.
.IP "-antialiasing %i"
Enables antialiasing. %i must be a power of 2.
.IP "-realtime_update"
When a gui based driver is used, it forces the update of the output at realtime.
.IP "-v"
Increases the verbosity.
.IP "-version / -ver"
Outputs the program version information and exits.
.IP "-help"
Outputs basic usage information and exits.
.SH AUTHOR
."BR bar (1)
Written by Nikos Papadopoulos <nikpapas at gmail dot com>
"
