language: cpp

os:
    - linux
    - osx

before_install:
    - if [ $TRAVIS_OS_NAME == osx   ]; then brew update && brew install glfw3 && brew install sdl2; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:pyglfw/pyglfw; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:george-edison55/precise-backports --yes; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo make-ssl-cert generate-default-snakeoil; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y --no-install-recommends libglew-dev libglfw3-dev libxrandr-dev libxi-dev libxxf86vm-dev; fi

script:
  - ./configure
  - make
