language: cpp

os:
    - linux
    - osx

allow_failures:
    - os: osx

install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:pyglfw/pyglfw; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y --no-install-recommends cmake libglew-dev libxrandr-dev libxi-dev libxxf86vm-dev libasound-dev; fi

    # GLFW 3.1.1 install
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq g++-4.8 gcc-4.8 libglew-dev libfreetype6-dev doxygen libharfbuzz-dev libxmu-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then unzip glfw-3.2.1.zip; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then cd glfw-3.2.1; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then make; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo make install; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then cd ..; fi
    - if [ $TRAVIS_OS_NAME == osx   ]; then brew update; fi
    - if [ $TRAVIS_OS_NAME == osx   ]; then brew tap homebrew/versions; fi
    - if [ $TRAVIS_OS_NAME == osx   ]; then brew install glfw3; fi

script:
    - ./configure
    - make
