language: cpp
os:
- linux
- osx
matrix:
  allow_failures:
  - os: osx
deploy:
  provider: releases
  api_key:
    secure: l2amX1gIefACeX5D6VhN7ylVcmNaKVlbjbygbEcy2Zx7D6MpUdg3H/tqPthwy7f8fFD4BPbAvuEDEpVAfvrFu4CI/Rrs7cSLYYX3DsvVgUS0ZDI4MRJ3tmM2IcyapcRFrC26MvauZ7VF4ZM86bU91KOR6W9hI+ZKfuSfYBije4Qu4JMd1L3OrorkdmWqzru566tNMlQ4jrjHx21Vmi25lcEif8frmj5SdgUtTcOt6Mk/TvtuYb3fIQie+NwHY3X5YVhcYwlMNc9N+2eNTBudWhPDz+Avu9iLJWI/bieb/OaR/pzkC+2zRVpAnam5TTNTi+wv+pHZ/96gX7xFMXUwJ4KoeUSqdEVvJma8ny/nizovKyPkm/xAMNBWvZAEhQrHwB7iu5xSUkbAF1yudTYEgPKAUyYhU84vv2MoXCWI/As44NnATWTSJeAV8bGIXc9iGB8lntYqHZ9fO55w3w97tFOGBzIaacXEhwvjlT83S3u5NN2LmzL3gwQJSzUfpsiJIVuPzgpdVTakz3AQLz/pS3mCzXE7kGWBLy+iyKxaBDY/1KUiQhfTA3ZpOti3EfyHMNZ7mq2cT9xYruHXXj/9wZYzeHUVazDYyJhEnw9muKXcgnfH/XPuhttYWJ/gmVpYSoZ+YVL1mTsq5UT2Aw1KnVnkAlWSzqKlqcQGD8AsUhA=
  file: bin/xtracer
  on:
    tags: true
    repo: 4rknova/xtracer
    all_branches: true
