language: cpp

os:
    - linux
    - osx

allow_failures:
    - os: osx

install:
    - 'if [ $TRAVIS_OS_NAME == linux ]; then
        sudo add-apt-repository -y ppa:pyglfw/pyglfw;
        sudo apt-get update;
        sudo apt-get install -y --no-install-recommends cmake libglew-dev libxrandr-dev libxi-dev libxxf86vm-dev libasound-dev;
        sudo apt-get install -qq g++-4.8 gcc-4.8 libglew-dev libfreetype6-dev doxygen libharfbuzz-dev libxmu-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev;
        wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
        unzip glfw-3.2.1.zip
        cd glfw-3.2.1
        cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
        make
        sudo make install
        cd ..
      fi'
    - if [ $TRAVIS_OS_NAME == osx]; then brew install glfw3 for glfw3; fi

script:
    - ./configure
    - make
