#ifndef XTGUI_FEATURE_H_INCLUDED
#define XTGUI_FEATURE_H_INCLUDED

#define FEATURE_INCLUDED (1)
#define FEATURE_EXCLUDED (0)
#define FEATURE_IS_INCLUDED(X) (X == FEATURE_INCLUDED)

#endif /* XTGUI_FEATURE_H_INCLUDED */
