# embed_kernel.cmake
# Called by add_custom_command to convert pathtracer.cl into an includeable C++ header.
# Expands one level of #include "..." directives relative to the input file's directory
# so that per-material .cl files are inlined before the string is embedded.
#
# Usage (from CMakeLists.txt add_custom_command):
#   cmake -DINPUT_FILE=<path/to/pathtracer.cl> -DOUTPUT_FILE=<path/to/pathtracer_cl_src.h> -P embed_kernel.cmake

cmake_minimum_required(VERSION 3.10)

if (NOT INPUT_FILE OR NOT OUTPUT_FILE)
    message(FATAL_ERROR "embed_kernel.cmake: INPUT_FILE and OUTPUT_FILE must be set")
endif()

get_filename_component(KERNEL_DIR "${INPUT_FILE}" DIRECTORY)

file(READ "${INPUT_FILE}" kernel_src)

# Expand #include "..." directives (one level, relative to the kernel directory).
string(REGEX MATCHALL "#include \"[^\"]+\"" include_directives "${kernel_src}")
foreach(directive ${include_directives})
    string(REGEX REPLACE "#include \"([^\"]+)\"" "\\1" inc_filename "${directive}")
    set(inc_path "${KERNEL_DIR}/${inc_filename}")
    if(EXISTS "${inc_path}")
        file(READ "${inc_path}" inc_content)
        string(REPLACE "${directive}" "${inc_content}" kernel_src "${kernel_src}")
    else()
        message(WARNING "embed_kernel.cmake: included file not found: ${inc_path}")
    endif()
endforeach()

# Escape for C string literal
string(REPLACE "\\" "\\\\" kernel_src "${kernel_src}")
string(REPLACE "\"" "\\\"" kernel_src "${kernel_src}")
string(REPLACE "\n" "\\n\"\n\"" kernel_src "${kernel_src}")

file(WRITE "${OUTPUT_FILE}"
"/* Auto-generated by embed_kernel.cmake — do not edit. */
#ifndef PATHTRACER_CL_SRC_H_INCLUDED
#define PATHTRACER_CL_SRC_H_INCLUDED
static const char * const k_opencl_pathtracer_src =
\"${kernel_src}\"
;
#endif /* PATHTRACER_CL_SRC_H_INCLUDED */
")
