#ifndef XTRACER_MATDEFS_H_INCLUDED
#define XTRACER_MATDEFS_H_INCLUDED

#define MAT_SAMPLER_AMBIENT   "ambient"
#define MAT_SAMPLER_DIFFUSE   "diffuse"
#define MAT_SAMPLER_SPECULAR  "specular"
#define MAT_SAMPLER_EMISSIVE  "emissive"

#endif /* XTRACER_MATDEFS_H_INCLUDED */
