#ifndef XTCORE_MATDEFS_H_INCLUDED
#define XTCORE_MATDEFS_H_INCLUDED

#define MAT_SAMPLER_AMBIENT      "ambient"
#define MAT_SAMPLER_DIFFUSE      "diffuse"
#define MAT_SAMPLER_SPECULAR     "specular"
#define MAT_SAMPLER_EMISSIVE     "emissive"
#define MAT_SAMPLER_NORMAL       "normal"
#define MAT_SAMPLER_BASE_COLOR   "base_color"
#define MAT_SAMPLER_TRANSMISSION "transmission"
#define MAT_SAMPLER_ABSORPTION_COLOR "absorption_color"
#define MAT_SAMPLER_SUBSURFACE_COLOR "subsurface_color"
#define MAT_SAMPLER_SUBSURFACE_RADIUS "subsurface_radius"
#define MAT_SAMPLER_SHEEN_COLOR  "sheen_color"
#define MAT_SAMPLER_TRANSLUCENCY_COLOR "translucency_color"
#define MAT_SAMPLER_ROUGHNESS    "roughness"
#define MAT_SAMPLER_METALLIC     "metallic"

#define MAT_SCALART_REFLECTANCE  "reflectance"
#define MAT_SCALART_TRANSPARENCY "transparency"
#define MAT_SCALART_EXPONENT     "exponent"
#define MAT_SCALART_IOR          "ior"
#define MAT_SCALART_ROUGHNESS    "roughness"
#define MAT_SCALART_METALLIC     "metallic"
#define MAT_SCALART_SPECULAR     "specular"
#define MAT_SCALART_CLEARCOAT    "clearcoat"
#define MAT_SCALART_CLEARCOAT_ROUGHNESS "clearcoat_roughness"
#define MAT_SCALART_ABSORPTION_DISTANCE "absorption_distance"
#define MAT_SCALART_ANISOTROPY   "anisotropy"
#define MAT_SCALART_ANISOTROPY_ROTATION "anisotropy_rotation"
#define MAT_SCALART_SUBSURFACE   "subsurface"
#define MAT_SCALART_THICKNESS    "thickness"
#define MAT_SCALART_SHEEN        "sheen"
#define MAT_SCALART_TRANSLUCENCY "translucency"

#endif /* XTCORE_MATDEFS_H_INCLUDED */
