name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libgl1-mesa-dev libglx-mesa0 libglew-dev libglfw3-dev libasound2-dev
      - name: Build
        run: cmake ./CMakeLists.txt && make
